id: A86F9F413
base_file: fDEEE.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:12:53.984608
  last_modified_at: 2022-05-30 23:12:53.984634
